/*
Oregon State University
Author: James Lee
Course: CS 361 Winter 2023
Assignment: Course Project
Description: Schema and sample data for scheduler program
*/

-- MySQL Script generated by MySQL Workbench
-- Sun 29 Jan 2023 05:52:46 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sessions` (
  `sessionID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sessionDate` DATE NULL,
  `sessionTime` TIME NULL,
  `sessionLength` TINYINT(3) NULL DEFAULT 50,
  `sessionCapacity` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`sessionID`),
  UNIQUE INDEX `sessionID_UNIQUE` (`sessionID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `userID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(256) NOT NULL,
  `password` VARCHAR(1024) NOT NULL,
  `authLvl` INT UNSIGNED NOT NULL DEFAULT 2,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instructors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instructors` (
  `instructorID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(256) NOT NULL,
  `lastName` VARCHAR(256) NULL,
  `email` VARCHAR(256) NOT NULL,
  `phone` BIGINT UNSIGNED NULL,
  `userID` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`instructorID`),
  UNIQUE INDEX `instructorID_UNIQUE` (`instructorID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Instructors_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`Users` (`userID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `clientID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(256) NOT NULL,
  `lastName` VARCHAR(256) NULL,
  `email` VARCHAR(256) NOT NULL,
  `phone` BIGINT UNSIGNED NULL,
  `userID` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`clientID`),
  UNIQUE INDEX `instructorID_UNIQUE` (`clientID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Clients_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`Users` (`userID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`SessionsDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SessionsDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SessionsDetails` (
  `sessionDetailsID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clientID` BIGINT UNSIGNED NULL,
  `instructorID` BIGINT UNSIGNED NULL,
  `sessionID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`sessionDetailsID`),
  UNIQUE INDEX `sessionDetailsID_UNIQUE` (`sessionDetailsID` ASC) VISIBLE,
  UNIQUE INDEX `session_UNIQUE` (`clientID` ASC, `instructorID` ASC, `sessionID` ASC) VISIBLE,
  CONSTRAINT `fk_Instructors_SessionDetails_instructorID`
    FOREIGN KEY (`instructorID`)
    REFERENCES `mydb`.`Instructors` (`instructorID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clients_SessionDetails_clientID`
    FOREIGN KEY (`clientID`)
    REFERENCES `mydb`.`Clients` (`clientID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sessions_SessionDetails_sessionID`
    FOREIGN KEY (`sessionID`)
    REFERENCES `mydb`.`Sessions` (`sessionID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- ------------------
-- SAMPLE INSERT DATA
-- ------------------

-- SESSIONS SAMPLE DATA
INSERT INTO  `mydb`.`Sessions`
(
  `sessionDate`,
  `sessionTime`,
  `sessionLength`,
  `sessionCapacity`
)
VALUES
(
  '2023-01-29',
  '10:00:00',
  DEFAULT,
  DEFAULT
),
(
  '2023-01-29',
  '11:00:00',
  DEFAULT,
  2
),
(
  '2023-01-29',
  '13:00:00',
  DEFAULT,
  DEFAULT
),
(
  '2023-01-29',
  '14:00:00',
  DEFAULT,
  DEFAULT
),
(
  '2023-01-29',
  '15:00:00',
  DEFAULT,
  DEFAULT
);

SELECT * FROM Sessions;

-- USERS SAMPLE DATA
INSERT INTO  `mydb`.`Users`
(
  `userName`,
  `password`,
  `authLvl`
)
VALUES
(
  'admin',
  '8f6c989c0f601cf1b2d4b240dd740fe2',
  0
),
(
  'instructor1',
  '8f6c989c0f601cf1b2d4b240dd740fe2',
  1
),
(
  'client1',
  '8f6c989c0f601cf1b2d4b240dd740fe2',
  2
),
(
  'client2',
  '8f6c989c0f601cf1b2d4b240dd740fe2',
  2
);

SELECT * FROM Users;

INSERT INTO  `mydb`.`Instructors`
(
  `firstName`,
  `lastName`,
  `email`,
  `phone`,
  `userID`
)
VALUES
(
  'Jane',
  'Doe',
  'jane@fake.com',
  5554440002,
  (
    SELECT userID FROM Users
    WHERE userName = 'instructor1'
  )
);

SELECT * FROM Instructors;

-- CLIENTS SAMPLE DATA
INSERT INTO  `mydb`.`Clients`
(
  `firstName`,
  `lastName`,
  `email`,
  `phone`,
  `userID`
)
VALUES
(
  'Jeff',
  'Doe',
  'jeff@fake.com',
  5554440003,
  (
    SELECT userID FROM Users
    WHERE userName = 'client1'
  )
),
(
  'Jessica',
  'Doe',
  'jessica@fake.com',
  5554440004,
  (
    SELECT userID FROM Users
    WHERE userName = 'client2'
  )
);

SELECT * FROM Clients;

-- SESSION DETAILS (INTERSECTION TABLE) SAMPLE DATA
INSERT INTO  `mydb`.`SessionsDetails`
(
  `clientID`,
  `instructorID`,
  `sessionID`
)
VALUES
(
  (SELECT `clientID` FROM `Clients` WHERE `Clients`.`email` = 'jessica@fake.com'),
  1,
  1 
),
(
  (SELECT `clientID` FROM `Clients` WHERE `Clients`.`email` = 'jessica@fake.com'),
  1,
  2 
),
(
  (SELECT `clientID` FROM `Clients` WHERE `Clients`.`email` = 'jeff@fake.com'),
  1,
  2 
);

SELECT * FROM SessionsDetails;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
